In [1]:
import dask.dataframe as dd
from src.data.storage import get_local_data_path

In [2]:
file_path_coordinates = get_local_data_path(
    path=["external", "geopy"],
    file_name="coordinates",
    file_format=".parquet",
)

ddf_coordinates = dd.read_parquet(file_path_coordinates)
ddf_coordinates.head()

                city               zone        lat        lon
0              cuneo              cuneo  44.458070   7.558137
1      lamezia-terme      lamezia-terme  38.964507  16.302145
2  montecatini-terme  montecatini-terme  43.883179  10.770953
3            sanremo            sanremo  43.819825   7.774883
4            tortona            tortona  44.896660   8.864128

In [3]:
file_path_stores = get_local_data_path(
    path=["interim", "store"],
)
ddf_stores = dd.read_parquet(file_path_stores)
ddf_stores.head()

/home/giacomorebecchi/mambaforge/envs/food-pricing/lib/python3.9/site-packages/dask/dataframe/core.py:7480: UserWarning: Insufficient elements for `head`. 5 elements requested, only 2 elements available. Try passing larger `npartitions` to `head`.
  warnings.warn(

,id,name,hasOrderNotes,tipMessage,menuDisabled,deliversToCustomerLocation,menuId,drnId,currencyCode,currencySymbol,...,location_address_address1,location_address_postCode,location_address_neighborhood,location_address_city,location_address_country,filePath,store,menuRow,city,zone
0,414349,Happy Pizza,False,nan,True,False,1919033,e5ee91da-0472-40a5-9525-e9ea6744d65d,EUR,€,...,"Via Reich 62, Bergamo, 24020",nan,Alzano Lombardo,bergamo,IT,food-delivery-crawler/data/processed/deliveroo...,happy-pizza-bergamo,0,bergamo,alzano-lombardo
0,276784,Pony Burger,False,nan,True,False,391036,906f63a0-0d73-47ed-9c93-35f2236bc73b,EUR,€,...,"Via Agostino Gemelli, 17, Bergamo, 24124",nan,Alzano Lombardo,bergamo,IT,food-delivery-crawler/data/processed/deliveroo...,pony-burger,0,bergamo,alzano-lombardo

In [4]:
file_path_menus = get_local_data_path(
    path=["interim", "menu"],
)
ddf_menus = dd.read_parquet(file_path_menus)
ddf_menus.head()

,percentageDiscounted,name,popular,categoryId,modifierGroupIds,priceDiscounted,isSignatureExclusive,productInformation,nutritionalInfo,available,...,image_typeName,image_altText,image_url,image_type,image,filePath,store,menuRow,city,zone
0,nan,Panino kebab e bibita,False,138580330,['974463437'],nan,False,nan,nan,True,...,nan,nan,nan,nan,nan,food-delivery-crawler/data/processed/deliveroo...,happy-pizza-bergamo,0,bergamo,alzano-lombardo
1,nan,"Panino kebab, bibita e patatine",True,138580330,['974463437'],nan,False,nan,nan,True,...,nan,nan,nan,nan,nan,food-delivery-crawler/data/processed/deliveroo...,happy-pizza-bergamo,1,bergamo,alzano-lombardo
2,nan,Piadina kebab e bibita,False,138580330,['974463437'],nan,False,nan,nan,True,...,nan,nan,nan,nan,nan,food-delivery-crawler/data/processed/deliveroo...,happy-pizza-bergamo,2,bergamo,alzano-lombardo
3,nan,"Piadina kebab, bibita e patatine",False,138580330,['974463437'],nan,False,nan,nan,True,...,nan,nan,nan,nan,nan,food-delivery-crawler/data/processed/deliveroo...,happy-pizza-bergamo,3,bergamo,alzano-lombardo
4,nan,Piatto kebab e bibita,False,138580330,['974463437'],nan,False,nan,nan,True,...,nan,nan,nan,nan,nan,food-delivery-crawler/data/processed/deliveroo...,happy-pizza-bergamo,4,bergamo,alzano-lombardo

In [5]:
file_path_images = get_local_data_path(
    path=["interim", "images"],
)
ddf_images = dd.read_parquet(file_path_images)
ddf_images.head()

,imgPath,store,menuRow,format,city,zone
0,food-delivery-crawler/data/images/deliveroo.it...,pony-burger,0,.jpeg,bergamo,alzano-lombardo
1,food-delivery-crawler/data/images/deliveroo.it...,pony-burger,1,.jpeg,bergamo,alzano-lombardo
2,food-delivery-crawler/data/images/deliveroo.it...,pony-burger,10,.jpeg,bergamo,alzano-lombardo
3,food-delivery-crawler/data/images/deliveroo.it...,pony-burger,11,.jpeg,bergamo,alzano-lombardo
4,food-delivery-crawler/data/images/deliveroo.it...,pony-burger,12,.jpeg,bergamo,alzano-lombardo

In [6]:
file_path_dataset = get_local_data_path(
    path=["processed"],
    file_name="dataset",
    file_format=".parquet"
)
ddf_dataset = dd.read_parquet(file_path_dataset)
ddf_dataset.head()

/home/giacomorebecchi/mambaforge/envs/food-pricing/lib/python3.9/site-packages/dask/dataframe/core.py:7480: UserWarning: Insufficient elements for `head`. 5 elements requested, only 4 elements available. Try passing larger `npartitions` to `head`.
  warnings.warn(

,name,description,price_fractional,menuRow,store,lat,lon,imgPath,city,zone
54,Panino falafel e bibita,nan,650.0,6,happy-pizza-bergamo,45.733603,9.730494,None,bergamo,alzano-lombardo
55,Focaccia al crudo,"Crudo di Parma, olio di oliva e sale",650.0,108,happy-pizza-bergamo,45.733603,9.730494,None,bergamo,alzano-lombardo
56,Acqua frizzante 50cl,nan,100.0,121,happy-pizza-bergamo,45.733603,9.730494,None,bergamo,alzano-lombardo
57,Avocado bomb,"Burger di verdure verdi (cavolo riccio, brocco...",900.0,13,pony-burger,45.733603,9.730494,food-delivery-crawler/data/images/deliveroo.it...,bergamo,alzano-lombardo