In [1]:
import dask.dataframe as dd
from src.data.storage import dd_read_parquet
from src.data.config import (
    COORDINATES_TABLE,
    FULL_TABLE,
    IMAGES_TABLE,
    ITEMS_TABLE,
    Table,
)

REMOTE = True

In [3]:
def show_table(table: Table):
    path = table.remote_path if REMOTE else table.local_path
    ddf = dd_read_parquet(
        path=path,
        remote=REMOTE,
    )
    return ddf.head()

In [4]:
show_table(COORDINATES_TABLE)

                city               zone        lat        lon
0              cuneo              cuneo  44.458070   7.558137
1      lamezia-terme      lamezia-terme  38.964507  16.302145
2  montecatini-terme  montecatini-terme  43.883179  10.770953
3            sanremo            sanremo  43.819825   7.774883
4            tortona            tortona  44.896660   8.864128

In [5]:
show_table(IMAGES_TABLE)

,imgPath,store,menuRow,format,city,zone
0,food-delivery-crawler/data/images/deliveroo.it...,pony-burger,0,.jpeg,bergamo,alzano-lombardo
1,food-delivery-crawler/data/images/deliveroo.it...,pony-burger,1,.jpeg,bergamo,alzano-lombardo
2,food-delivery-crawler/data/images/deliveroo.it...,pony-burger,10,.jpeg,bergamo,alzano-lombardo
3,food-delivery-crawler/data/images/deliveroo.it...,pony-burger,11,.jpeg,bergamo,alzano-lombardo
4,food-delivery-crawler/data/images/deliveroo.it...,pony-burger,12,.jpeg,bergamo,alzano-lombardo

In [6]:
show_table(ITEMS_TABLE)

,percentageDiscounted,name,popular,categoryId,modifierGroupIds,priceDiscounted,isSignatureExclusive,productInformation,nutritionalInfo,available,...,image_typeName,image_altText,image_url,image_type,image,filePath,store,menuRow,city,zone
0,nan,Panino kebab e bibita,False,138580330,['974463437'],nan,False,nan,nan,True,...,nan,nan,nan,nan,nan,food-delivery-crawler/data/processed/deliveroo...,happy-pizza-bergamo,0,bergamo,alzano-lombardo
1,nan,"Panino kebab, bibita e patatine",True,138580330,['974463437'],nan,False,nan,nan,True,...,nan,nan,nan,nan,nan,food-delivery-crawler/data/processed/deliveroo...,happy-pizza-bergamo,1,bergamo,alzano-lombardo
2,nan,Piadina kebab e bibita,False,138580330,['974463437'],nan,False,nan,nan,True,...,nan,nan,nan,nan,nan,food-delivery-crawler/data/processed/deliveroo...,happy-pizza-bergamo,2,bergamo,alzano-lombardo
3,nan,"Piadina kebab, bibita e patatine",False,138580330,['974463437'],nan,False,nan,nan,True,...,nan,nan,nan,nan,nan,food-delivery-crawler/data/processed/deliveroo...,happy-pizza-bergamo,3,bergamo,alzano-lombardo
4,nan,Piatto kebab e bibita,False,138580330,['974463437'],nan,False,nan,nan,True,...,nan,nan,nan,nan,nan,food-delivery-crawler/data/processed/deliveroo...,happy-pizza-bergamo,4,bergamo,alzano-lombardo

In [7]:
show_table(FULL_TABLE)

,name,description,price_fractional,menuRow,store,lat,lon,imgPath,city,zone
7,Panino falafel e bibita,nan,650.0,6,happy-pizza-bergamo,45.733603,9.730494,None,bergamo,alzano-lombardo
8,Focaccia al crudo,"Crudo di Parma, olio di oliva e sale",650.0,108,happy-pizza-bergamo,45.733603,9.730494,None,bergamo,alzano-lombardo
9,Acqua frizzante 50cl,nan,100.0,121,happy-pizza-bergamo,45.733603,9.730494,None,bergamo,alzano-lombardo
10,Avocado bomb,"Burger di verdure verdi (cavolo riccio, brocco...",900.0,13,pony-burger,45.733603,9.730494,food-delivery-crawler/data/images/deliveroo.it...,bergamo,alzano-lombardo
7,Gamberetti e rucola,"Pomodoro, mozzarella, mazzancolle tropicali, r...",700.0,48,happy-pizza-bergamo,45.733603,9.730494,None,bergamo,alzano-lombardo

In [9]:
def check_table_length():
    path_full = FULL_TABLE.remote_path if REMOTE else FULL_TABLE.local_path
    path_items = ITEMS_TABLE.remote_path if REMOTE else ITEMS_TABLE.local_path
    assert (
        len(dd_read_parquet(path_full, REMOTE)) == len(dd_read_parquet(path_items, REMOTE))
        )

check_table_length()